// CITY with a controller, on game time: walk, emote wheel, get into a car (seated, hands on the wheel), drive, get out, photo mode.
import { launch } from './lib.mjs';
const t = await launch({ pad: process.env.PAD ?? 'xbox' });
const { page, shot, hold, stick, step, press, waitState, state, errors } = t;
await waitState('landing');
await t.wait(4000);
await page.evaluate(() => { window.nf.mode = 'city'; window.nf.enter(); });
console.log('state', await waitState('playing', 200));
await step(1);
await page.evaluate(() => { const nf = window.nf; nf.player.place(-5.2, 0.15, 22, -Math.PI / 2); nf.follow.yaw = -Math.PI / 2 + 0.6; nf.follow.snap(nf.player, nf.world.collision); });
await step(2);
await shot('city-01-by-car');
await hold('Down', true); await step(0.3);
await stick(1, 0, -1); await step(0.3);
await shot('city-02-wheel');
await hold('Down', false); await stick(1, 0, 0); await step(0.9);
await shot('city-03-wave');
console.log('emote', await page.evaluate(() => window.nf.player.emote?.id ?? null));
await step(2);
await press('X'); await step(1.2);
console.log('vehicle', await page.evaluate(() => window.nf.vehicle?.kind ?? null));
await shot('city-04-seated');
await hold('RT', true, 0, 0.8); await stick(0, -0.35, 0); await step(3);
await shot('city-05-driving');
await hold('RT', false); await stick(0, 0, 0); await hold('LT', true); await step(2.5); await hold('LT', false);
await press('B'); await step(1.5);
console.log('vehicle after B', await page.evaluate(() => window.nf.vehicle?.kind ?? null));
await shot('city-06-out');
await press('Up'); await step(0.5);
await stick(1, 0.6, -0.2); await step(0.8); await stick(1, 0, 0);
await press('RB'); await step(0.3);
await shot('city-07-photo');
await press('A'); await step(0.3);
await press('B'); await step(0.5);
console.log('state', await state(), 'errors', errors);
await t.browser.close();
